S01 us08
WildCodeSchool-2024-09/JS-Bdx-P2-vroom-vroom pull request #11
Opened 2024-11-20 10:11 UTC by Barre-Rapheel

2024-11-20 10:13 UTC, Aurelien-sys approved these changes
ok

2024-11-20 10:14 UTC, Aurelien-sys approved these changes

2024-11-20 10:14 UTC, Aurelien-sys approved these changes

2024-11-20 10:14 UTC, Aurelien-sys commented
ok

2024-11-20 10:40 UTC, Roxanne-Alezine approved these changes

2024-11-20 10:53 UTC, sarah-sdk requested changes

2024-11-20 10:53 UTC, sarah-sdk commented on client/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
tu as ajouté une autre police ?

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/App.tsx
il faut que tu crées une page sur react router, pour ne pas modifier le App.tsx

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/assets/images/1920px-Melbourne_Grand_Prix_Circuit,_March_22,_2018_SkySat_(cropped).jpg
il faut qu'il y ait une cohérence entre tes différentes images...
des images réelles ou des schémas c'est pas fou...
+ mets toutes tes images dans un dossier dans image stp :'(

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/components/CircuitList/index.tsx
> +  const fetchCircuits = useCallback(async () => {
async ? vraiment ?
genre tu peux réexpliquer ce code ?

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/pages/circuitPage/CircuitPage.tsx
> +    <div>
div...

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/components/CircuitList/index.tsx
> +    <div>
div...

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/components/CircuitList/index.tsx
> +      <ul className={styles["circuit-grid"]}>
cette façon d'écrire fonctionne ? c'est pas un "styles.nomDeTaClasse" ?

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/components/CircuitList/index.tsx
> +          <li key={circuit.circuitId} className={styles["circuit-item"]}>
cette façon d'écrire fonctionne ? c'est pas un "styles.nomDeTaClasse" ?

2024-11-20 10:53 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
ton style n'est pas en mobile first, il faut que tu refasses ton style pour avoir cette logique

2024-11-20 11:03 UTC, Barre-Rapheel commented on client/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
c'est la polices que t'avais donné.

2024-11-20 11:04 UTC, Barre-Rapheel commented on client/src/App.tsx
ma page est créé dans reactRouter

2024-11-20 11:05 UTC, Barre-Rapheel commented on client/src/assets/images/1920px-Melbourne_Grand_Prix_Circuit,_March_22,_2018_SkySat_(cropped).jpg
ok

2024-11-20 11:11 UTC, Barre-Rapheel commented on client/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
ok

2024-11-20 11:12 UTC, Barre-Rapheel commented on client/src/App.tsx
j'ai supprimer mon appel dans App.tsx et ça fonctionne

2024-11-20 11:15 UTC, Barre-Rapheel commented on client/src/assets/images/1920px-Melbourne_Grand_Prix_Circuit,_March_22,_2018_SkySat_(cropped).jpg
Dossier imagesCircuits créé dans asset

2024-11-20 11:22 UTC, Barre-Rapheel commented on client/src/pages/circuitPage/CircuitPage.tsx
> +    <div>
changement avec des fragments

2024-11-20 11:23 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +    <div>
changement avec des fragments

2024-11-20 12:59 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
Done

2024-11-20 13:40 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +      <ul className={styles["circuit-grid"]}>
J'ai un tiret dans le nom de ma clase circuit-grid je suis obligé de mettre des crochets

2024-11-20 13:43 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +      <ul className={styles["circuit-grid"]}>
J'ai un tiret dans le nom de ma classe c'est une manière d'écrire pour ne pas à avoir des erreurs

2024-11-20 13:43 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +          <li key={circuit.circuitId} className={styles["circuit-item"]}>
J'ai un tiret dans le nom de ma classe c'est une manière d'écrire pour ne pas à avoir des erreurs

2024-11-20 14:08 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +  const fetchCircuits = useCallback(async () => {
async  = asynchrones

vu que le fetch est une opération qui peut prendre du temps on rend la fonction asynchrones pour permettre de gérer des opérations sans bloquer l'exécution du programme 

await est utilisé pour attendre que le fetch et response.json() se terminent avant de passer aux lignes suivantes.

2024-11-20 14:09 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +  const fetchCircuits = useCallback(async () => {
async = asynchrones

vu que le fetch est une opération qui peut prendre du temps on rend la fonction asynchrones pour permettre de gérer des opérations sans bloquer l'exécution du programme

await est utilisé pour attendre que le fetch et response.json() se terminent avant de passer aux lignes suivantes.

2024-11-20 14:28 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +  const fetchCircuits = useCallback(async () => {
le code a été simplifié

2024-11-20 17:28 UTC, sarah-sdk requested changes

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  background-color: var(--dark) !important;
/!\ interdiction d'utiliser important !
le background color du body est déjà censé être réglé sur la couleur dark (dans le App.css)

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  background-color: var(--grey) !important;
/!\ interdiction d'utiliser important !

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  padding: 0;
check si t'as vraiment besoin de cette ligne, vu que le padding par défaut est à 0 il y a moyen qu'elle n'influence pas ton rendu
peut-être que si, mais à vérifier :)

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  margin: 0;
check si t'as vraiment besoin de cette ligne, vu que le margin par défaut est à 0 il y a moyen qu'elle n'influence pas ton rendu
peut-être que si, mais à vérifier :)

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  margin: var(--spacingXXS) 0 0;
si tu modifies seulement une valeur de margin, utilise plutôt un "margin-cotéQueTuVeuxModifier"

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
ton style est toujours pensé en priorité sur le desktop,
il faut que ton style "de base" corresponde à ta version mobile, et que tes media queries viennent modifier ce qui a besoin de l'être en version desktop (donc tu utiliseras plus des "min-width" que des "max-width")

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/assets/imagesCircuits/1920px-Melbourne_Grand_Prix_Circuit,_March_22_2018_SkySat_(cropped).jpg
c'est bien d'avoir tout regroupé dans un dossier :)
mais quand tu les ajouteras sur ta page, essaie de trouver un style cohérent entre tes différentes images (soit que des images réelles, ou que des schémas)

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/index.tsx
> +    fetch("https://corsproxy.io/?https://ergast.com/api/f1/2024/circuits.json")
à quoi correspond ce "https://corsproxy.io/?"

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/pages/circuitPage/CircuitPage.tsx
> +export default function CircuitPage() {
n'oublie pas d'importer le compte à rebours jusqu'à la prochaine course ;)

2024-11-20 17:28 UTC, sarah-sdk commented on client/src/components/CircuitList/index.tsx
> +        {circuits.map((circuit) => (
l'utilisation d'une figure me parait pertinent pour regrouper toutes les infos de chaque circuit, à confirmer avec Yoann demain si c'est le cas ou non

2024-11-20 17:31 UTC, Manon879 approved these changes

2024-11-21 08:19 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
> +  background-color: var(--dark) !important;
ligne 3 à 5 enlevé 
test ok

2024-11-21 08:24 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
> +  background-color: var(--grey) !important;
important enlevé
test ok

2024-11-21 08:57 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
> +  padding: 0;
ligne enlevé 
test ok

2024-11-21 08:59 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
> +  margin: 0;
ligne enlevé
test ok

2024-11-21 09:15 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
> +  margin: var(--spacingXXS) 0 0;
modification avec 
margin-top: var(--spacingXXS);

2024-11-21 09:40 UTC, Barre-Rapheel commented on client/src/assets/imagesCircuits/1920px-Melbourne_Grand_Prix_Circuit,_March_22_2018_SkySat_(cropped).jpg
la page circuit sera constitué que de photo réel

2024-11-21 10:10 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +    fetch("https://corsproxy.io/?https://ergast.com/api/f1/2024/circuits.json")
J'avais eu des problème de connexion vers l'API 
Le proxy CORS m'a permis de contournez le problème de connexion 
je l'ai enlevé ça refonctionne

2024-11-21 10:19 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
done

2024-11-21 15:11 UTC, Barre-Rapheel commented on client/src/pages/circuitPage/CircuitPage.tsx
> +export default function CircuitPage() {
done

2024-11-21 15:15 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +        {circuits.map((circuit) => (
dac on verra avec yoann pour l'utilisation d'une balise <figure>

2024-11-22 09:13 UTC, sarah-sdk reviewed
quelques petits trucs encore mais rien de bien méchant O:)

2024-11-22 09:13 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  max-width: 1200px;
valeur en px, non responsive, c'est mieux en rem

2024-11-22 09:13 UTC, sarah-sdk commented on client/src/components/CircuitList/index.tsx
> +        {circuits.map((circuit) => (
du coup, tu as demandé à Yoann pour la figure ? pas nécessaire ?

2024-11-22 09:29 UTC, Barre-Rapheel commented on client/src/components/CircuitList/CircuitList.module.css
> +  max-width: 1200px;
done

2024-11-22 09:36 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +        {circuits.map((circuit) => (
non pas encore

2024-11-22 09:51 UTC, Barre-Rapheel commented on client/src/components/CircuitList/index.tsx
> +        {circuits.map((circuit) => (
Vu avec Yoann l'utilisation d'une balise figure est plus pertinente

2024-11-25 08:27 UTC, sarah-sdk approved these changes
2-3 petites dernières corrections, mais sinon c'est good ! gg 💪🏼

2024-11-25 08:27 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  margin-bottom: 2rem;
pour ce genre de notation, tu peux faire un margin : x y (un des 2 gère le margin horizontal et l'autre le vertical, je ne sais jamais lequel des deux, faut test 🤣)

2024-11-25 08:27 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  margin: 0 auto;
tu vois, comme ici (voir le commentaire juste au dessus)

2024-11-25 08:27 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
> +  border-radius: 0.5rem;
pour les border radius, les px sont acceptés ;) car c'est une valeur fixe qui ne change pas en fonction de l'écran :)

2024-11-25 08:27 UTC, sarah-sdk commented on client/src/components/CircuitList/CircuitList.module.css
tu peux optimiser ton style en utilisant les variables "spacing" ;)

2024-11-25 08:27 UTC, merged